### ISSUE TITLE
Mixin Opacity

### ISSUE THREAD

**Issue by raphaelfabeni** [neysimoes/sass-mixins#4]
Hoje o mixin para opacidade é esse:

``` scss
@mixin opacity($value) {
     $ie: $value * 100;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=$ie)";
    filter: alpha(opacity=$ie);
    -khtml-opacity: $value;
     -moz-opacity: $value;
             opacity: $value;
}
```

Eu fiz alguns testes com esse mixin e aparentemente funcionou em todos os navegadores.

``` scss
@mixin opacity($value) {
    opacity: $value;
    filter: alpha(opacity=($value * 100));
}
```

No _Can I Use_ não encontrei nenhum prefixo. E fiz alguns testes no IE e o filter segurou a onda.
O que você acha?
